version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=host.docker.internal
      - POSTGRES_PORT=5432
      - POSTGRES_USER=morgan
      - POSTGRES_PASSWORD=wsg254731051
      - POSTGRES_DB=bizbrain
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-here
      - OPENAI_API_KEY=your-openai-api-key-here
      - PYTHONPATH=/app
      - ENVIRONMENT=production  # 设置为生产环境
    depends_on:
      - redis
    volumes:
      - ./backend:/app
      - ./backend/app:/app/app

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes  # 启用持久化

volumes:
  redis_data:
    driver: local
    driver_opts:
      type: none
      device: ./redis_data
      o: bind

networks:
  default:
    driver: bridge

 